# Docker Compose file for BJJ club management app
services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: bjjuser
      POSTGRES_PASSWORD: bjjpass
      POSTGRES_DB: bjj_club_db
    volumes:
      - ./mg-backend/01-init-members.sql:/docker-entrypoint-initdb.d/01-init-members.sql:ro
      - ./mg-backend/02-init-class-coupons.sql:/docker-entrypoint-initdb.d/02-init-class-coupons.sql:ro
      - ./mg-backend/03-membership_plans.sql:/docker-entrypoint-initdb.d/03-membership_plans.sql:ro
      - ./mg-backend/04-init-member-payments.sql:/docker-entrypoint-initdb.d/04-init-member-payments.sql:ro
      - ./mg-backend/05-init-indexes.sql:/docker-entrypoint-initdb.d/05-init-indexes.sql:ro
      - ./mg-backend/06-seed-data.sql:/docker-entrypoint-initdb.d/06-seed-data.sql:ro
    ports:
      - "5432:5432"  

  mg-api:
    build:
      context: ./mg-api
    ports:
      - "3000:3000"
    user: "1001:1001"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bjj_club_db
      - DB_USER=bjjuser
      - DB_PASSWORD=bjjpass
      - IMAGE_STORAGE_PATH=/data/images
    volumes:
      - ./mg-api:/app
      - /app/node_modules
      - images-data:/data/images
    depends_on:
      - db
    command: ["npm", "run", "dev"]

  mg-frontend:
    build:
      context: ./mg-frontend
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://mg-api:3000/api
    volumes:
      - ./mg-frontend:/app
      - /app/node_modules
    depends_on:
      - mg-api
    command: ["npm", "run", "dev"]



  dd-admin:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db  

volumes:
  db-data:
  images-data: